#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: ${SERVICE_PORT}
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /admin
      path-mapping:
        health: health-check
info:
  app:
    name: Certificate
    version: ${API_VERSION}
spring:
  profiles: default
  security:
    user:
      name: ${SERVICE_USER}
      password: ${SERVICE_PASSWORD}
    jwt:
      jwks: ${SECURITY_JWT_JWKS}
      iss: ${SECURITY_JWT_ISS}
      aud: ${SECURITY_JWT_AUD}
permissions:
  service:
    scheme: ${PERMISSIONS_SERVICE_SCHEME}
    host: ${PERMISSIONS_SERVICE_HOST}
    port: ${PERMISSIONS_SERVICE_PORT}
    user: ${PERMISSIONS_SERVICE_USERNAME}
    password: ${PERMISSIONS_SERVICE_PASSWORD}
    connectionTimeout: ${PERMISSIONS_SERVICE_CONNECTION_TIMEOUT}
    readTimeout: ${PERMISSIONS_SERVICE_CONNECTION_TIMEOUT}
frontendNotification:
  service:
    scheme: ${FRONTEND_NOTIFICATION_SERVICE_SCHEME}
    host: ${FRONTEND_NOTIFICATION_SERVICE_HOST}
    port: ${FRONTEND_NOTIFICATION_SERVICE_PORT}
    user: ${FRONTEND_NOTIFICATION_SERVICE_USERNAME}
    password: ${FRONTEND_NOTIFICATION_SERVICE_PASSWORD}
service:
  security:
    token-feature-switch: false
    default-roles: inspector, importer