#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  port: ${SERVICE_PORT}
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /admin
      path-mapping:
        health: health-check
info:
  app:
    name: Certificate
    version: ${API_VERSION}
spring:
  profiles: default
  security:
    user:
      name: ${SERVICE_USER}
      password: ${SERVICE_PASSWORD}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD};trustServerCertificate=${TRUST_SERVER_CERTIFICATE};hostNameInCertificate=*.database.windows.net;encrypt=true;
    continueOnError: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
service:
  security:
      token-feature-switch: false
      default-roles: inspector, importer
permissions:
  service:
   scheme: ${PERMISSIONS_SERVICE_SCHEME}
   host: ${PERMISSIONS_SERVICE_HOST}
   port: ${PERMISSIONS_SERVICE_PORT}
   user: ${PERMISSIONS_SERVICE_USERNAME}
   password: ${PERMISSIONS_SERVICE_PASSWORD}
   connectionTimeout: ${PERMISSIONS_SERVICE_CONNECTION_TIMEOUT}
   readTimeout: ${PERMISSIONS_SERVICE_CONNECTION_TIMEOUT}
